name: Terraform Reusable Workflow

permissions:
    id-token: write
    contents: read

on:
  workflow_call:
    inputs:
      terraform-command:
        required: true
        type: string

      working-directory:
        required: false
        type: string
        default: "."

      aws-region:
        required: false
        type: string
        default: "us-east-1"

    secrets:
      role-to-assume:
        required: true


jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.role-to-assume }}
          aws-region: ${{ inputs.aws-region }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Command
        run: terraform ${{ inputs.terraform-command }}